# This file was generated by GoReleaser. DO NOT EDIT.
cask "qode" do
  version "0.2.0-beta"

  on_macos do
    on_intel do
      sha256 "abc9117165e235cf118f0cf3d1a0c9a50bf42240a1b543ad70844598c924249a"
      url "https://github.com/nqode-io/qode/releases/download/v#{version}/qode_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0a38e382bb50ec97f3063c9387d39bbea834e0288f14ba698bc28bde719268ab"
      url "https://github.com/nqode-io/qode/releases/download/v#{version}/qode_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b8c9472085e773b10550bc3b349226dd2f25ccf854d69f6e6931fd860957c786"
      url "https://github.com/nqode-io/qode/releases/download/v#{version}/qode_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "296cac9fbee173ed4d33fac32d4501ea3cddb895327d225f99a0eade14103eca"
      url "https://github.com/nqode-io/qode/releases/download/v#{version}/qode_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "qode"
  desc "Generates structured AI prompts for a standardized developer workflow"
  homepage "https://github.com/nqode-io/qode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qode"

  postflight do
    system_command "#{staged_path}/qode", args: ["--version"]
  end

  # No zap stanza required

end
