# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qode < Formula
  desc "Generates structured AI prompts for a standardized developer workflow"
  homepage "https://github.com/nqode-io/qode"
  version "0.3.3-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nqode-io/qode/releases/download/v0.3.3-beta/qode_v0.3.3-beta_darwin_amd64.tar.gz"
      sha256 "3ee94a1c58f195d9308a9fb668a0c91d5ff67e0bfb178ec34e43ec7bd1121aa6"

      define_method(:install) do
        bin.install "qode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nqode-io/qode/releases/download/v0.3.3-beta/qode_v0.3.3-beta_darwin_arm64.tar.gz"
      sha256 "4694f6586bfcc661828b39eed1e16254e35d887412894f82ec861f13561f8e1f"

      define_method(:install) do
        bin.install "qode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nqode-io/qode/releases/download/v0.3.3-beta/qode_v0.3.3-beta_linux_amd64.tar.gz"
      sha256 "d784fe4750720bb90fd9dfad6551c154771eb17a3f85ea1f96476e46a66b4685"
      define_method(:install) do
        bin.install "qode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nqode-io/qode/releases/download/v0.3.3-beta/qode_v0.3.3-beta_linux_arm64.tar.gz"
      sha256 "aa0a89cc00913e2d62dac4decf4027df0fcfee0608de90b0d2c93a85f87e89e0"
      define_method(:install) do
        bin.install "qode"
      end
    end
  end

  test do
    system "#{bin}/qode", "--version"
  end
end
